Repository seeyouletter/seeyouletter-be, pull requests merged in 2022-12, with the labels that each got.

#2 fix: github action syntax 에러 수정
  .github/workflows/api-sample-pull-request.yml
  build.gradle
Labels: bug

#7 chore(husky): husky, commitizen 및cz-customizable config 추가
  .cz-config.js
  .gitignore
  .husky/prepare-commit-msg
  package-lock.json
  package.json
Labels: 📦 CHORE, 💫 CI/CD, 🚧 NEED REVIEW

#13 Develop
  .cz-config.js
  .gitignore
  .husky/prepare-commit-msg
  README.md
  package-lock.json
  package.json
Labels: 📦 CHORE, 💫 CI/CD, 📝 DOCS

#11 User Entity 생성
  api-letter/src/test/java/com/seeyouletter/api_letter/ApiLetterApplicationTest.java
  domain-member/src/main/java/com/seeyouletter/domain_member/config/DomainMemberAutoConfiguration.java
  domain-member/src/main/java/com/seeyouletter/domain_member/entity/User.java
  domain-member/src/main/java/com/seeyouletter/domain_member/entity/Users.java
  domain-member/src/main/java/com/seeyouletter/domain_member/enums/GenderType.java
  domain-member/src/main/java/com/seeyouletter/domain_member/enums/converter/GenderTypeConverter.java
  domain-member/src/main/java/com/seeyouletter/domain_member/repository/UserRepository.java
  domain-member/src/main/java/com/seeyouletter/domain_member/repository/UsersRepository.java
  domain-member/src/test/java/com/seeyouletter/domain_member/entity/UserTest.java
  domain-member/src/test/java/com/seeyouletter/domain_member/entity/UsersTest.java
  domain-member/src/test/java/com/seeyouletter/domain_member/repository/UserRepositoryTest.java
  domain-member/src/test/java/com/seeyouletter/domain_member/repository/UsersRepositoryTest.java
  domain-member/src/test/resources/application.yml
Labels: 💌 FEATURE, 🚧 NEED REVIEW, ✅ TEST
