Repository seeyouletter/seeyouletter-be, pull requests merged in 2023-02, with the labels that each got.

#34 로컬 및 개발 서버 cors 허용 설정 추가
  api-member/src/main/java/com/seeyouletter/api_member/config/AuthorizationServerConfiguration.java
  api-member/src/main/java/com/seeyouletter/api_member/config/ResourceServiceConfiguration.java
  api-member/src/main/java/com/seeyouletter/api_member/config/SecurityConfiguration.java
  api-member/src/main/java/com/seeyouletter/api_member/controller/DefaultController.java
Labels: 📦 CHORE

#37 style(test): assertThat 사용하는 테스트 코드 hamcrest에서 assertj로 변경
  api-member/src/main/java/com/seeyouletter/api_member/config/AuthorizationServerConfiguration.java
  api-member/src/main/java/com/seeyouletter/api_member/config/SecurityConfiguration.java
  api-member/src/test/java/com/seeyouletter/api_member/e2e/Oauth2AuthorizationTest.java
  api-member/src/test/java/com/seeyouletter/api_member/integration/RedisOauth2AuthorizationServiceTest.java
  domain-letter/src/test/java/com/seeyouletter/domain_letter/collection/LetterTest.java
  domain-letter/src/test/java/com/seeyouletter/domain_letter/repository/LetterRepositoryTest.java
  domain-member/src/test/java/com/seeyouletter/domain_member/entity/UserTest.java
  domain-member/src/test/java/com/seeyouletter/domain_member/repository/UserRepositoryTest.java
Labels: ✅ TEST

#33 feat(api-member): seeyouletter 로그인 구현(AuthenticationProvider token생성)
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/PrincipalDetails.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/service/CustomOAuth2UserService.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/service/UserDetailsServiceImpl.java
  api-member/src/main/java/com/seeyouletter/api_member/config/SecurityConfiguration.java
  api-member/src/main/resources/application-local.yml
  api-member/src/main/resources/data.sql
  api-member/src/test/resources/application-test.yml
  domain-member/src/main/java/com/seeyouletter/domain_member/entity/User.java
  domain-member/src/main/java/com/seeyouletter/domain_member/repository/UserRepository.java
Labels: 💌 FEATURE

#39 dev profile 네이버, 카카오 callback redirect uri를 수정한다.
  api-member/src/main/resources/application-dev.yml
  api-member/src/main/resources/application-local.yml
Labels: 📦 CHORE

#38 로컬 및 개발 서버의 cors 허용과 forward header 전략을 설정하고 인증 서버 클라이언트 redirect_uri를 변경한다.
  api-member/src/main/java/com/seeyouletter/api_member/config/AuthorizationServerConfiguration.java
  api-member/src/main/java/com/seeyouletter/api_member/config/SecurityConfiguration.java
  api-member/src/main/resources/application-dev.yml
Labels: 📦 CHORE

#41 chore(api-member): dev 환경에서 임시 admin 계정 정보 insert 적용
  api-member/src/main/resources/application-dev.yml
Labels: 📦 CHORE

#45 feat(api-member): rest API 로그인 추가 적용
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/CustomHttpConfigurer.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/RestAuthenticationProcessingFilter.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/value/LoginRequest.java
  api-member/src/main/java/com/seeyouletter/api_member/config/SecurityConfiguration.java
Labels: 💌 FEATURE
