Repository seeyouletter/seeyouletter-be, pull requests merged in 2023-03, with the labels that each got.

#47 fix(api-member): principalDetails 삭제, 로그인 계정 클래스 분리
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/CustomOAuth2User.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/PrincipalDetails.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/service/CustomOAuth2UserService.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/service/UserDetailsServiceImpl.java
Labels: 🐛 BUG

#46 CustomOauth2User 객체를 RedisOauth2AuthorizationService에서 JSON 역직렬화를 할 수 없는 문제를 해결한다.
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/CustomAuthorization.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/CustomAuthorizationMixIn.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/CustomOauth2UserMixIn.java
  api-member/src/main/java/com/seeyouletter/api_member/config/RedisOauth2AuthorizationService.java
  api-member/src/test/java/com/seeyouletter/api_member/config/WithMockOauth2User.java
  api-member/src/test/java/com/seeyouletter/api_member/config/WithMockOauth2UserSecurityContextFactory.java
  api-member/src/test/java/com/seeyouletter/api_member/e2e/Oauth2AuthorizationTest.java
Labels: 🐛 BUG

#48 oauth2 authorization server userinfo endpoint 응답 필드를 추가한다.
  api-letter/src/test/java/com/seeyouletter/api_letter/IntegrationTestContext.java
  api-member/src/docs/asciidoc/oauth2-authorization-server.adoc
  api-member/src/main/java/com/seeyouletter/api_member/config/AuthorizationServerConfiguration.java
  api-member/src/main/java/com/seeyouletter/api_member/config/CustomOauth2TokenCustomizer.java
  api-member/src/main/java/com/seeyouletter/api_member/exception/ResourceNotFoundException.java
  api-member/src/main/java/com/seeyouletter/api_member/service/UserService.java
  api-member/src/test/java/com/seeyouletter/api_member/IntegrationTestContext.java
  api-member/src/test/java/com/seeyouletter/api_member/e2e/Oauth2AuthorizationTest.java
  api-member/src/test/java/com/seeyouletter/api_member/integration/RedisOauth2AuthorizationServiceTest.java
Labels: 💌 FEATURE

#50 oauth2 custom 구현체에서 발생한 에러를 oauth2 에러 핸들러에서 처리할 수 있도록 수정한다.
  api-member/src/docs/asciidoc/oauth2-authorization-server.adoc
  api-member/src/main/java/com/seeyouletter/api_member/config/CustomOauth2TokenCustomizer.java
  api-member/src/main/java/com/seeyouletter/api_member/config/RedisOauth2AuthorizationService.java
Labels: 💌 FEATURE

#52 feat(api-member): restAPI 로그인 성공, 실패 핸들러 추가, 폼로그인 redirectUrl 부분 수정
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/RestLoginFailureHandler.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/RestLoginHttpConfigurer.java
  api-member/src/main/java/com/seeyouletter/api_member/auth/config/RestLoginSuccessHandler.java
  api-member/src/main/java/com/seeyouletter/api_member/config/SecurityConfiguration.java
  api-member/src/main/resources/static/favicon.ico
  api-member/src/main/resources/static/index.html
Labels: 💌 FEATURE

#62 개발 환경 cors 허용 origin 목록의 오타를 수정한다.
  api-member/src/main/resources/application-dev.yml
Labels: 🐛 BUG

#59 test(api-member): Rest API 로그인 테스트 코드를 추가한다.
  api-member/src/test/java/com/seeyouletter/api_member/e2e/RestAuthenticationTest.java
Labels: ✅ TEST
