Repository seeyouletter/seeyouletter-be, pull requests merged in 2023-01, with the labels that each got.

#22 Resource Server에서 Authorization Server가 생성한 엑세스 토큰으로 인가를 처리할 수 있도록 구현한다.
  api-letter/build.gradle
  api-letter/src/main/java/com/seeyouletter/api_letter/config/ResourceServiceConfiguration.java
  api-letter/src/main/resources/application-local.yml
  api-letter/src/test/resources/application-test.yml
  api-member/src/main/java/com/seeyouletter/api_member/config/ResourceServiceConfiguration.java
  api-member/src/main/resources/application-local.yml
  api-member/src/test/resources/application-test.yml
Labels: 📦 CHORE, 💌 FEATURE

#23 메모리에서 관리하기 적합한 데이터들을 Redis를 사용하여 저장 및 사용할 수 있도록 의존성과 설정을 추가한다.
  api-letter/src/test/java/com/seeyouletter/api_letter/IntegrationTestContext.java
  api-member/build.gradle
  api-member/src/main/java/com/seeyouletter/api_member/config/RedisConfiguration.java
  api-member/src/test/java/com/seeyouletter/api_member/IntegrationTestContext.java
  docker/docker-compose-local.yml
Labels: 📦 CHORE, 💌 FEATURE, 🚧 NEED REVIEW

#25 testcontainers가 class가 아닌 application context 범위로 라이프사이클이 적용되도록 변경한다.
  api-letter/src/test/java/com/seeyouletter/api_letter/IntegrationTestContext.java
  api-member/build.gradle
  api-member/src/test/java/com/seeyouletter/api_member/IntegrationTestContext.java
  domain-letter/build.gradle
  domain-letter/src/test/java/com/seeyouletter/domain_letter/MongoTestContext.java
Labels: 🐛 BUG, 🚧 NEED REVIEW

#26 fix(workflow): gradle wrapper를 cache하도록 변경하고 불필요하게 전체 모듈을 build하지 않도록…
  .github/workflows/api-letter-pull-request.yml
  .github/workflows/api-member-pull-request.yml
  .github/workflows/test-coverage.yml
Labels: 🐛 BUG, 💫 CI/CD

#30 oauth2 authorization server api 문서 작성
  api-member/src/docs/asciidoc/oauth2-authorization-server.adoc
  api-member/src/test/java/com/seeyouletter/api_member/e2e/Oauth2AuthorizationTest.java
Labels: 📝 DOCS

#31 개발 서버 배포를 위한 애플리케이션 설정 및 workflow 작성
  .github/workflows/api-member-pull-request.yml
  .github/workflows/develop-api-letter-deploy.yml
  .github/workflows/develop-api-member-deploy.yml
  api-letter/build.gradle
  api-letter/src/main/java/com/seeyouletter/api_letter/config/JasyptConfig.java
  api-letter/src/main/resources/application-dev.yml
  api-member/src/main/java/com/seeyouletter/api_member/config/AuthorizationServerConfiguration.java
  api-member/src/main/resources/application-dev.yml
Labels: 📦 CHORE, 💫 CI/CD
